config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  devise_for :users
  resource :home, only: [:show]
  get "home/about" => "homes#show", as: "homes_about"
  delete 'books/:id' => 'books#destroy', as: 'destroy_books'
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true,
                   length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :configure_permitted_parameters, if: :devise_controller?
      def after_sign_in_path_for(resource) 
          user_path(resource)
      end

     protected
     def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
     devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
     end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	def new
		@book=Book.new
    end
    def create
    	@book=Book.new(book_params)
        @book.user_id=current_user.id
        @user = current_user
        @books=Book.all
    	if @book.save
           flash[:notice] = "You have creatad book successfully."
    	   redirect_to book_path(@book.id)
        else
            render :index
        end
    end

    def index
        @user = current_user
    	@books=Book.all
        @book = Book.new
    end

    def show
    	@book = Book.find(params[:id])
    	@user = @book.user
    end

    def edit
        @book = Book.find(params[:id])
        if @book.user_id == current_user.id
            render :edit
    	else
            redirect_to books_path
        end
    end

    def update
         @book = Book.find(params[:id])
         if @book.update(book_params)
            flash[:notice] = "You have updated book successfully."
            redirect_to book_path(@book.id)
        else
            render :edit
        end
    end

    def destroy
    	book=Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end

    private
    def book_params
    	params.require(:book).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @user = current_user
  end

  def show
  	@user = User.find(params[:id])
    @books=@user.books
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id == current_user.id
        render :edit
    else
        redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_booklists.html.erb
<h2>Books</h2>

<table class="table table-hover">
	<thead>
 	<tr>
 		<th class="col-xs-2"></th>
 		<th class="col-xs-4">Title</th>
 		<th class="col-xs-6">Opinion</th>
 	</tr>
    </thead>
	<tbody>
	<% books.each do |book| %>
	<tr>
		<td>
			<%= link_to user_path(book.user_id) do %>
			<%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"40x40" %>
			<% end %>
		</td>
		<td>
		    <%= link_to book_path(book.id) do %>
		    <%= book.title %>
		    <% end %>
		</td>
		<td><%= book.body %></td>
	</tr>
	 <% end %>
    </tbody>
</table>

app/views/books/_new.html.erb
<h2>New book</h2>
<%= form_for(Book.new) do |f| %>
<label><b>Title</b></label>
<%= f.text_field :title %>
<label><b>Opinion</b></label>
<%=f.text_area :body %>
<br>
<%= f.submit "Create Book", class: "btn btn-primary btn-block"  %>
<% end %>

app/views/books/edit.html.erb
<div class="col-xs-6 col-xs-offset-3">
<%= render partial:"layouts/error_messages", locals: {book: @book} %>

<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
<h4><b>Title</b></h4>
<%= f.text_field :title %>
<h4><b>Opinion</b></h4>
<%= f.text_area :body %>
<br>
<%= f.submit "Update Book", class: "btn btn-primary btn-block"%>
<% end %>

<%=link_to "Show", book_path(@book.id) %>
<span>|</span>
<%=link_to "Back", books_path %>

</div>

app/views/books/index.html.erb
<%= render partial:"layouts/error_messages", locals: {book: @book} %>
    <div class="row">
    	<div class="col-xs-3">
			<%= render partial:"users/user_profile", locals: {user: @user} %>

			<%= render partial:"new" %>
		</div>

        <div class="col-xs-9">
			<%= render partial:"booklists",locals: {books: @books} %>
		</div>
	</div>

app/views/books/show.html.erb

    <div class="row">
    	<div class="col-xs-3">
			<%= render partial:"users/user_profile", locals: {user: @user} %>

			<%= render partial:"new" %>
		</div>

        <div class="col-xs-9">
			<h1>Book detail</h1>
			<table class="table">
			<tbody>
			<tr>
				<td>
				  <%= link_to user_path(@book.user_id) do %>
				  <%= attachment_image_tag @book.user, :profile_image,format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %>
				  <% end %>
				  <br>
				   <%= link_to user_path(@book.user_id) do %>
				   <%= @user.name %>
				   <% end %>
				</td>
				<td>
				   <%= @book.title %>
				</td>
				<td>
				   <%= @book.body %>
				</td>

				<% if @user.id == current_user.id %>
				　<td>
					<%=link_to edit_book_path(@book.id) do %>
					<button class="btn btn-success">Edit</button>
			        <% end %>
				  </td>
				　<td><%=link_to destroy_books_path(@book.id), method: :delete,"data-confirm" => "本当に消しますか?" do %>
					<button class="btn btn-danger">Destroy</button>
			        <% end %>
				  </td>
				<% end %>
			</tr>
			</tbody>
		</table>
		</div>
	</div>

app/views/homes/show.html.erb
<h1>
	Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers!</strong>
</h1>

app/views/homes/top.html.erb
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3">
			<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers!!</strong></h1>

			<p>In  <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers,</strong></p>

			<p>you can share and exchange your opinions , inpressions , and emotions</p>

			<p>about various books!</p>

        <div class="row">
			<%=link_to "Log in", new_user_session_path, class: "btn btn-info btn-block col-xs-10 col-xs-offset-1" %>
		</div>

        <div class="row">
			<%=link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block col-xs-10 col-xs-offset-1" %>
		</div>

       </div>
	</div>

app/views/layouts/_error_messages.html.erb
<% if book.errors.any? %>
<div class="error_explanation">
    <h2><%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul>
      <% book.errors.full_messages.each do |message| %>
        ><%= message %></li>
      <% end %>
    </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <div class="navbar-text">Bookers</div>
        </div>

       <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.id) do %>
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path do %>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path do %>
            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path do %>
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
            <% end %>
          </li>
          <li>
            <%= link_to homes_about_path do %>
            <span class="glyphicon glyphicon-link" aria-hidden="true"></span>About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>login
            <% end %>
          </li>
        <% end %>
  </ul>
</div>
</nav>

<div class="container">
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p class="alert"><%= flash[:alert] %></p>
  <% end %>

  <%= yield %>
</div>

  <footer class="footer">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
           <p>CopyRight Infratop.inc</p>
        </div>
    </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/_user_profile.html.erb
<h2>User info</h2>
    <p><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"%></p>

    <table class="table">
    	<tbody>
		    <tr>
		    	<td><b>name</b></td>
		    	<td><b><%= user.name %></b></td>
		    </tr>
		    <tr>
		    	<td><b>introduction</b></td>
		    	<td><b><%= user.introduction %></b></td>
		    </tr>
        </tbody>
    </table>

    <% if user.id == current_user.id %>
        <p>
            <%= link_to edit_user_path(user) do %>
            <button type="button" class="btn btn-default btn-block">
                <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            </button>
            <% end %>
        </p>
    <% else %>
        <p>
            <%= link_to user_path(current_user.id) do %>
            <button type="button" class="btn btn-default btn-block" >
                 <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            </button>
            <% end %>
        </p>
    <% end %>

app/views/users/edit.html.erb
<div class="col-xs-3">
<% if @user.errors.any? %>
<div class="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        ><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h2>User info</h2>
 <%= form_for(@user) do |f| %>
  <label>Name</label>
  <%= f.text_field :name, autofocus: true %>
  <br>
  <label>Image</label>
  <%= f.attachment_field :profile_image%>
  <br>
  <label>Introduction</label>
  <%= f.text_area :introduction %>
  <br>
  <%= f.submit "Update User" %>
 <% end %>
</div>

app/views/users/index.html.erb

    <div class="row">
    	<div class="col-xs-3">
          <%= render partial:"user_profile", locals: {user: @user} %>

          <%= render partial:"books/new" %>
        </div>

        <div class="col-xs-9">
			<h2>Users</h2>

			<table class="table">
				<thead>
			 	<tr>
			 		<th class="col-xs-3">image</th>
			 		<th class="col-xs-6">name</th>
			 		<th class="col-xs-3"></th>
			 	</tr>
			    </thead>
				<tbody>
				<% @users.each do |user| %>
				<tr>
					<td>
						<%= attachment_image_tag user, :profile_image,format: 'jpeg', fallback: "no_image.jpg", size:"40x40" %>
					</td>
					<td>
					    <%= user.name %>
					</td>
					<td>
						<%= link_to "Show", user_path(user.id) %>
					</td>
				</tr>
				 <% end %>
			    </tbody>
			</table>
		</div>
	</div>

app/views/users/show.html.erb
    <div class="row">
    	<div class="col-xs-3">
          <%= render partial:"user_profile", locals: {user: @user} %>

          <%= render partial:"books/new" %>
        </div>
    

        <div class="col-xs-9">
           <%= render partial:"books/booklists" ,locals: {books: @books} %>
        </div>
    </div>